export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const CREATE_PROFESSIONAL_SUCCESS = 'CREATE_PROFESSIONAL_SUCCESS';
export const CREATE_PROFESSIONAL_ERROR = 'CREATE_PROFESSIONAL_ERROR';
export const GET_MODALITIES = 'GET_MODALITIES';
export const FETCH_PROFESSIONALS = 'FETCH_PROFESSIONALS';
export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';