export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const CREATE_PROFESSIONAL_SUCCESS = 'CREATE_PROFESSIONAL_SUCCESS';
export const CREATE_PROFESSIONAL_ERROR = 'CREATE_PROFESSIONAL_ERROR';

